// prisma/seed-data/states.ts
// Cannabis Law State Data - December 2025
// Sources: NCSL, NORML, State Government Sites

export const stateData = [
  // ============================================
  // RECREATIONAL + MEDICAL STATES (24 + DC)
  // ============================================
  {
    name: "Alaska",
    slug: "alaska",
    abbreviation: "AK",
    legalStatus: "RECREATIONAL",
    recLegal: true,
    recPossessionLimit: "1 oz usable, 7g concentrate",
    recPurchaseLimit: "1 oz flower, 7g concentrate per transaction",
    recHomeCultivation: "6 plants (3 mature) per adult, 12 per household",
    recMinAge: 21,
    recEffectiveDate: new Date("2015-02-24"),
    medLegal: true,
    medPossessionLimit: "1 oz usable",
    medHomeCultivation: "6 plants (3 mature)",
    medQualifyingConditions: "Cancer, HIV/AIDS, glaucoma, chronic pain, cachexia, PTSD, and others",
    officialResourceUrl: "https://www.commerce.alaska.gov/web/amco/MarijuanaInitiative.aspx",
    summaryText: "Alaska legalized recreational cannabis in 2014. Adults 21+ can purchase up to 1 oz and grow 6 plants at home.",
  },
  {
    name: "Arizona",
    slug: "arizona",
    abbreviation: "AZ",
    legalStatus: "RECREATIONAL",
    recLegal: true,
    recPossessionLimit: "1 oz flower, 5g concentrate",
    recPurchaseLimit: "1 oz flower, 5g concentrate",
    recHomeCultivation: "6 plants per adult, 12 per household if 2+ adults",
    recMinAge: 21,
    recEffectiveDate: new Date("2020-11-30"),
    medLegal: true,
    medPossessionLimit: "2.5 oz per 14 days",
    medQualifyingConditions: "Cancer, HIV/AIDS, hepatitis C, ALS, Crohn's, PTSD, chronic pain, and others",
    officialResourceUrl: "https://azdhs.gov/licensing/marijuana/index.php",
    summaryText: "Arizona voters approved recreational cannabis in 2020. Adults can possess 1 oz and grow up to 6 plants.",
  },
  {
    name: "California",
    slug: "california",
    abbreviation: "CA",
    legalStatus: "RECREATIONAL",
    recLegal: true,
    recPossessionLimit: "28.5g flower, 8g concentrate",
    recPurchaseLimit: "28.5g flower, 8g concentrate per day",
    recHomeCultivation: "6 plants per residence",
    recMinAge: 21,
    recEffectiveDate: new Date("2016-11-08"),
    medLegal: true,
    medPossessionLimit: "8 oz or amount determined by physician",
    medQualifyingConditions: "Any condition where medical use is appropriate and recommended by physician",
    officialResourceUrl: "https://cannabis.ca.gov/",
    summaryText: "California, the first state to legalize medical cannabis (1996) and recreational in 2016. Adults can possess 28.5g and grow 6 plants.",
  },
  {
    name: "Colorado",
    slug: "colorado",
    abbreviation: "CO",
    legalStatus: "RECREATIONAL",
    recLegal: true,
    recPossessionLimit: "2 oz flower, 8g concentrate",
    recPurchaseLimit: "1 oz per transaction for residents, 1 oz for visitors",
    recHomeCultivation: "6 plants per adult (3 flowering), max 12 per household",
    recMinAge: 21,
    recEffectiveDate: new Date("2012-12-10"),
    medLegal: true,
    medPossessionLimit: "2 oz usable",
    medQualifyingConditions: "Cancer, glaucoma, HIV/AIDS, cachexia, persistent muscle spasms, seizures, severe nausea, severe pain, PTSD",
    officialResourceUrl: "https://sbg.colorado.gov/med",
    summaryText: "Colorado was the first state to legalize recreational cannabis (2012). Adults can possess 2 oz and grow 6 plants.",
  },
  {
    name: "Connecticut",
    slug: "connecticut",
    abbreviation: "CT",
    legalStatus: "RECREATIONAL",
    recLegal: true,
    recPossessionLimit: "1.5 oz on person, 5 oz at home",
    recPurchaseLimit: "1 oz flower per transaction",
    recHomeCultivation: "3 mature, 3 immature plants per adult (max 12 per household) - starts July 2025",
    recMinAge: 21,
    recEffectiveDate: new Date("2021-07-01"),
    medLegal: true,
    medPossessionLimit: "2.5 oz per 30 days",
    medQualifyingConditions: "Cancer, HIV/AIDS, Parkinson's, MS, epilepsy, PTSD, chronic pain, and others",
    officialResourceUrl: "https://portal.ct.gov/DCP/Medical-Marijuana-Program/Medical-Marijuana-Program",
    summaryText: "Connecticut legalized recreational cannabis in 2021. Adults can possess 1.5 oz in public and 5 oz at home.",
  },
  {
    name: "Delaware",
    slug: "delaware",
    abbreviation: "DE",
    legalStatus: "RECREATIONAL",
    recLegal: true,
    recPossessionLimit: "1 oz",
    recPurchaseLimit: "1 oz",
    recHomeCultivation: "Not permitted",
    recMinAge: 21,
    recEffectiveDate: new Date("2023-04-23"),
    medLegal: true,
    medPossessionLimit: "6 oz per month",
    medQualifyingConditions: "Cancer, HIV/AIDS, hepatitis C, ALS, Alzheimer's, PTSD, autism, and others",
    officialResourceUrl: "https://dhss.delaware.gov/dhss/dph/hsp/medmarhome.html",
    summaryText: "Delaware legalized recreational cannabis in 2023. Adults can possess 1 oz but home cultivation is not allowed.",
  },
  {
    name: "Illinois",
    slug: "illinois",
    abbreviation: "IL",
    legalStatus: "RECREATIONAL",
    recLegal: true,
    recPossessionLimit: "30g flower, 5g concentrate (residents); 15g/2.5g (visitors)",
    recPurchaseLimit: "30g flower, 5g concentrate, 500mg edibles (residents)",
    recHomeCultivation: "5 plants for medical patients only; not permitted for recreational",
    recMinAge: 21,
    recEffectiveDate: new Date("2020-01-01"),
    medLegal: true,
    medPossessionLimit: "2.5 oz per 14 days",
    medHomeCultivation: "5 plants",
    medQualifyingConditions: "40+ qualifying conditions including cancer, HIV, PTSD, chronic pain",
    officialResourceUrl: "https://www.idfpr.com/profs/adultusecan.asp",
    summaryText: "Illinois legalized recreational cannabis in 2020. Residents can possess 30g flower. Home growing for medical only.",
  },
  {
    name: "Maine",
    slug: "maine",
    abbreviation: "ME",
    legalStatus: "RECREATIONAL",
    recLegal: true,
    recPossessionLimit: "2.5 oz",
    recPurchaseLimit: "2.5 oz flower, 5g concentrate",
    recHomeCultivation: "3 mature, 12 immature plants",
    recMinAge: 21,
    recEffectiveDate: new Date("2016-11-08"),
    medLegal: true,
    medPossessionLimit: "2.5 oz per 15 days",
    medQualifyingConditions: "Any condition for which physician would recommend cannabis",
    officialResourceUrl: "https://www.maine.gov/dafs/ocp/",
    summaryText: "Maine legalized recreational cannabis in 2016. Adults can possess 2.5 oz and grow 3 mature plants.",
  },
  {
    name: "Maryland",
    slug: "maryland",
    abbreviation: "MD",
    legalStatus: "RECREATIONAL",
    recLegal: true,
    recPossessionLimit: "1.5 oz flower, 12g concentrate",
    recPurchaseLimit: "1.5 oz per transaction",
    recHomeCultivation: "2 plants per person, 4 per household",
    recMinAge: 21,
    recEffectiveDate: new Date("2023-07-01"),
    medLegal: true,
    medPossessionLimit: "4 oz per 30 days",
    medQualifyingConditions: "Chronic pain, PTSD, seizures, glaucoma, and other conditions",
    officialResourceUrl: "https://mmcc.maryland.gov/",
    summaryText: "Maryland legalized recreational cannabis in 2023. Adults can possess 1.5 oz and grow 2 plants per person.",
  },
  {
    name: "Massachusetts",
    slug: "massachusetts",
    abbreviation: "MA",
    legalStatus: "RECREATIONAL",
    recLegal: true,
    recPossessionLimit: "1 oz in public, 10 oz at home",
    recPurchaseLimit: "1 oz flower, 5g concentrate",
    recHomeCultivation: "6 plants per adult, 12 per household",
    recMinAge: 21,
    recEffectiveDate: new Date("2016-12-15"),
    medLegal: true,
    medPossessionLimit: "10 oz per 60 days",
    medQualifyingConditions: "Cancer, glaucoma, HIV/AIDS, hepatitis C, ALS, Crohn's, Parkinson's, MS, and others",
    officialResourceUrl: "https://masscannabiscontrol.com/",
    summaryText: "Massachusetts legalized recreational cannabis in 2016. Adults can possess 1 oz publicly and grow 6 plants.",
  },
  {
    name: "Michigan",
    slug: "michigan",
    abbreviation: "MI",
    legalStatus: "RECREATIONAL",
    recLegal: true,
    recPossessionLimit: "2.5 oz in public, 10 oz at home",
    recPurchaseLimit: "2.5 oz per transaction",
    recHomeCultivation: "12 plants per household",
    recMinAge: 21,
    recEffectiveDate: new Date("2018-12-06"),
    medLegal: true,
    medPossessionLimit: "2.5 oz",
    medHomeCultivation: "12 plants",
    medQualifyingConditions: "Cancer, glaucoma, HIV/AIDS, hepatitis C, ALS, Crohn's, chronic pain, PTSD, and others",
    officialResourceUrl: "https://www.michigan.gov/cra",
    summaryText: "Michigan legalized recreational cannabis in 2018. Adults can possess 2.5 oz publicly and grow 12 plants.",
  },
  {
    name: "Minnesota",
    slug: "minnesota",
    abbreviation: "MN",
    legalStatus: "RECREATIONAL",
    recLegal: true,
    recPossessionLimit: "2 oz flower, 8g concentrate in public",
    recPurchaseLimit: "2 oz flower per transaction",
    recHomeCultivation: "8 plants (4 mature) per household",
    recMinAge: 21,
    recEffectiveDate: new Date("2023-08-01"),
    medLegal: true,
    medPossessionLimit: "Determined by patient's certifying healthcare practitioner",
    medQualifyingConditions: "Cancer, glaucoma, HIV/AIDS, Tourette's, ALS, seizures, MS, Crohn's, chronic pain, PTSD",
    officialResourceUrl: "https://www.ocm.mn.gov/",
    summaryText: "Minnesota legalized recreational cannabis in 2023. Adults can possess 2 oz flower and grow 8 plants.",
  },
  {
    name: "Missouri",
    slug: "missouri",
    abbreviation: "MO",
    legalStatus: "RECREATIONAL",
    recLegal: true,
    recPossessionLimit: "3 oz",
    recPurchaseLimit: "3 oz per day",
    recHomeCultivation: "6 flowering, 6 non-flowering, 6 clones per adult",
    recMinAge: 21,
    recEffectiveDate: new Date("2022-12-08"),
    medLegal: true,
    medPossessionLimit: "6 oz per month",
    medQualifyingConditions: "Cancer, epilepsy, glaucoma, HIV/AIDS, chronic pain, PTSD, and others",
    officialResourceUrl: "https://cannabis.mo.gov/",
    summaryText: "Missouri voters approved recreational cannabis in 2022. Adults can possess 3 oz and grow 6 flowering plants.",
  },
  {
    name: "Montana",
    slug: "montana",
    abbreviation: "MT",
    legalStatus: "RECREATIONAL",
    recLegal: true,
    recPossessionLimit: "1 oz",
    recPurchaseLimit: "1 oz",
    recHomeCultivation: "4 mature plants, 4 seedlings per adult",
    recMinAge: 21,
    recEffectiveDate: new Date("2021-01-01"),
    medLegal: true,
    medPossessionLimit: "1 oz usable",
    medQualifyingConditions: "Cancer, glaucoma, HIV/AIDS, Crohn's, epilepsy, MS, chronic pain, PTSD, and others",
    officialResourceUrl: "https://mtrevenue.gov/cannabis/",
    summaryText: "Montana legalized recreational cannabis in 2020. Adults can possess 1 oz and grow 4 mature plants.",
  },
  {
    name: "Nevada",
    slug: "nevada",
    abbreviation: "NV",
    legalStatus: "RECREATIONAL",
    recLegal: true,
    recPossessionLimit: "1 oz flower, 3.5g concentrate",
    recPurchaseLimit: "1 oz flower per transaction",
    recHomeCultivation: "6 plants per person if more than 25 miles from dispensary",
    recMinAge: 21,
    recEffectiveDate: new Date("2017-01-01"),
    medLegal: true,
    medPossessionLimit: "2.5 oz per 14 days",
    medQualifyingConditions: "Cancer, glaucoma, HIV/AIDS, PTSD, cachexia, persistent muscle spasms, seizures, severe nausea, severe pain",
    officialResourceUrl: "https://ccb.nv.gov/",
    summaryText: "Nevada legalized recreational cannabis in 2016. Adults can possess 1 oz. Home cultivation allowed if 25+ miles from dispensary.",
  },
  {
    name: "New Jersey",
    slug: "new-jersey",
    abbreviation: "NJ",
    legalStatus: "RECREATIONAL",
    recLegal: true,
    recPossessionLimit: "1 oz",
    recPurchaseLimit: "1 oz per transaction",
    recHomeCultivation: "Not permitted",
    recMinAge: 21,
    recEffectiveDate: new Date("2021-02-22"),
    medLegal: true,
    medPossessionLimit: "3 oz per 30 days",
    medQualifyingConditions: "Cancer, HIV/AIDS, ALS, MS, muscular dystrophy, IBD, chronic pain, anxiety, PTSD, and others",
    officialResourceUrl: "https://www.nj.gov/cannabis/",
    summaryText: "New Jersey legalized recreational cannabis in 2020. Adults can possess 1 oz but home growing is not allowed.",
  },
  {
    name: "New Mexico",
    slug: "new-mexico",
    abbreviation: "NM",
    legalStatus: "RECREATIONAL",
    recLegal: true,
    recPossessionLimit: "2 oz flower, 16g concentrate, 800mg edibles",
    recPurchaseLimit: "2 oz per day",
    recHomeCultivation: "6 mature, 6 immature plants per adult",
    recMinAge: 21,
    recEffectiveDate: new Date("2021-06-29"),
    medLegal: true,
    medPossessionLimit: "15 oz per 90 days",
    medQualifyingConditions: "Cancer, glaucoma, HIV/AIDS, MS, epilepsy, spinal cord damage, PTSD, chronic pain, and others",
    officialResourceUrl: "https://www.rld.nm.gov/cannabis/",
    summaryText: "New Mexico legalized recreational cannabis in 2021. Adults can possess 2 oz and grow 6 mature plants.",
  },
  {
    name: "New York",
    slug: "new-york",
    abbreviation: "NY",
    legalStatus: "RECREATIONAL",
    recLegal: true,
    recPossessionLimit: "3 oz flower, 24g concentrate",
    recPurchaseLimit: "3 oz flower per transaction",
    recHomeCultivation: "6 plants per person (3 mature, 3 immature), 12 per household",
    recMinAge: 21,
    recEffectiveDate: new Date("2021-03-31"),
    medLegal: true,
    medPossessionLimit: "60-day supply",
    medQualifyingConditions: "Cancer, HIV/AIDS, ALS, Parkinson's, MS, epilepsy, IBD, chronic pain, PTSD, and others",
    officialResourceUrl: "https://cannabis.ny.gov/",
    summaryText: "New York legalized recreational cannabis in 2021. Adults can possess 3 oz flower and grow 6 plants.",
  },
  {
    name: "Ohio",
    slug: "ohio",
    abbreviation: "OH",
    legalStatus: "RECREATIONAL",
    recLegal: true,
    recPossessionLimit: "2.5 oz flower, 15g concentrate",
    recPurchaseLimit: "2.5 oz per day",
    recHomeCultivation: "6 plants per adult, 12 per household",
    recMinAge: 21,
    recEffectiveDate: new Date("2023-12-07"),
    medLegal: true,
    medPossessionLimit: "90-day supply (up to 8 oz per 90 days)",
    medQualifyingConditions: "Cancer, HIV/AIDS, ALS, Alzheimer's, Crohn's, epilepsy, fibromyalgia, glaucoma, MS, Parkinson's, PTSD, chronic pain, and others",
    officialResourceUrl: "https://www.com.ohio.gov/cannabis",
    summaryText: "Ohio voters approved recreational cannabis in 2023. Adults can possess 2.5 oz and grow 6 plants.",
  },
  {
    name: "Oregon",
    slug: "oregon",
    abbreviation: "OR",
    legalStatus: "RECREATIONAL",
    recLegal: true,
    recPossessionLimit: "1 oz in public, 8 oz at home",
    recPurchaseLimit: "1 oz flower, 5g concentrate, 16 oz edibles per day",
    recHomeCultivation: "4 plants per household",
    recMinAge: 21,
    recEffectiveDate: new Date("2015-07-01"),
    medLegal: true,
    medPossessionLimit: "24 oz usable, 6 mature plants, 18 seedlings",
    medQualifyingConditions: "Cancer, glaucoma, HIV/AIDS, PTSD, chronic pain, cachexia, severe nausea, seizures, muscle spasms",
    officialResourceUrl: "https://www.oregon.gov/olcc/marijuana/pages/default.aspx",
    summaryText: "Oregon legalized recreational cannabis in 2014. Adults can possess 1 oz in public and grow 4 plants at home.",
  },
  {
    name: "Rhode Island",
    slug: "rhode-island",
    abbreviation: "RI",
    legalStatus: "RECREATIONAL",
    recLegal: true,
    recPossessionLimit: "1 oz",
    recPurchaseLimit: "1 oz per transaction",
    recHomeCultivation: "6 plants per person (3 mature), 12 per household",
    recMinAge: 21,
    recEffectiveDate: new Date("2022-05-25"),
    medLegal: true,
    medPossessionLimit: "2.5 oz",
    medQualifyingConditions: "Cancer, glaucoma, HIV/AIDS, hepatitis C, Crohn's, Alzheimer's, chronic pain, PTSD, and others",
    officialResourceUrl: "https://dbr.ri.gov/cannabis/",
    summaryText: "Rhode Island legalized recreational cannabis in 2022. Adults can possess 1 oz and grow 6 plants.",
  },
  {
    name: "Vermont",
    slug: "vermont",
    abbreviation: "VT",
    legalStatus: "RECREATIONAL",
    recLegal: true,
    recPossessionLimit: "1 oz",
    recPurchaseLimit: "1 oz per transaction",
    recHomeCultivation: "6 plants (2 mature) per household",
    recMinAge: 21,
    recEffectiveDate: new Date("2018-07-01"),
    medLegal: true,
    medPossessionLimit: "2 oz",
    medQualifyingConditions: "Cancer, HIV/AIDS, MS, Crohn's, Parkinson's, PTSD, chronic pain, and others",
    officialResourceUrl: "https://ccb.vermont.gov/",
    summaryText: "Vermont was the first state to legalize through legislature (2018). Adults can possess 1 oz and grow 6 plants.",
  },
  {
    name: "Virginia",
    slug: "virginia",
    abbreviation: "VA",
    legalStatus: "RECREATIONAL",
    recLegal: true,
    recPossessionLimit: "1 oz",
    recPurchaseLimit: "No retail sales yet - medical dispensaries only",
    recHomeCultivation: "4 plants per household",
    recMinAge: 21,
    recEffectiveDate: new Date("2021-07-01"),
    medLegal: true,
    medPossessionLimit: "4 oz per 30 days",
    medQualifyingConditions: "Any condition diagnosed by a practitioner",
    officialResourceUrl: "https://www.cca.virginia.gov/",
    summaryText: "Virginia legalized possession in 2021 but retail sales not yet operating. Adults can possess 1 oz and grow 4 plants.",
  },
  {
    name: "Washington",
    slug: "washington",
    abbreviation: "WA",
    legalStatus: "RECREATIONAL",
    recLegal: true,
    recPossessionLimit: "1 oz flower, 7g concentrate, 16 oz edibles",
    recPurchaseLimit: "1 oz per transaction",
    recHomeCultivation: "Not permitted for recreational",
    recMinAge: 21,
    recEffectiveDate: new Date("2012-12-06"),
    medLegal: true,
    medPossessionLimit: "3 oz usable",
    medHomeCultivation: "6 plants for medical patients",
    medQualifyingConditions: "Cancer, HIV, MS, epilepsy, Crohn's, hepatitis C, chronic renal failure, glaucoma, PTSD, chronic pain",
    officialResourceUrl: "https://lcb.wa.gov/mj2020/home",
    summaryText: "Washington was one of the first states to legalize recreational cannabis (2012). Adults can possess 1 oz but can't home grow.",
  },
  {
    name: "District of Columbia",
    slug: "district-of-columbia",
    abbreviation: "DC",
    legalStatus: "RECREATIONAL",
    recLegal: true,
    recPossessionLimit: "2 oz",
    recPurchaseLimit: "No commercial sales - gifting only",
    recHomeCultivation: "6 plants per adult (3 mature), 12 per household",
    recMinAge: 21,
    recEffectiveDate: new Date("2015-02-26"),
    medLegal: true,
    medPossessionLimit: "4 oz per month",
    medQualifyingConditions: "Any condition for which a physician recommends use",
    officialResourceUrl: "https://abra.dc.gov/",
    summaryText: "DC legalized recreational cannabis in 2014 but commercial sales remain banned. Gifting is common. Adults can possess 2 oz and grow 6 plants.",
  },

  // ============================================
  // MEDICAL ONLY STATES
  // ============================================
  {
    name: "Alabama",
    slug: "alabama",
    abbreviation: "AL",
    legalStatus: "MEDICAL",
    recLegal: false,
    medLegal: true,
    medPossessionLimit: "70 daily doses (varies by product type)",
    medQualifyingConditions: "Cancer, HIV/AIDS, epilepsy, chronic pain, PTSD, autism, Crohn's, Parkinson's, and others",
    medHowToApply: "Register with Alabama Medical Cannabis Commission after obtaining physician certification",
    officialResourceUrl: "https://amcc.alabama.gov/",
    summaryText: "Alabama legalized medical cannabis in 2021. Smoking flower is not permitted. Dispensaries opening in 2025.",
    penaltiesOverview: "Recreational possession: Misdemeanor up to 1 year, felony for subsequent offenses",
  },
  {
    name: "Arkansas",
    slug: "arkansas",
    abbreviation: "AR",
    legalStatus: "MEDICAL",
    recLegal: false,
    medLegal: true,
    medPossessionLimit: "2.5 oz per 14 days",
    medQualifyingConditions: "Cancer, glaucoma, HIV/AIDS, hepatitis C, ALS, Tourette's, Crohn's, fibromyalgia, PTSD, severe arthritis, and others",
    medHowToApply: "Get certification from licensed physician, apply through Arkansas Department of Health",
    officialResourceUrl: "https://www.healthy.arkansas.gov/programs-services/topics/medical-marijuana",
    summaryText: "Arkansas voters approved medical cannabis in 2016. Patients can possess up to 2.5 oz per 14-day period.",
    penaltiesOverview: "Recreational possession: Under 4 oz is misdemeanor, over 4 oz is felony",
  },
  {
    name: "Florida",
    slug: "florida",
    abbreviation: "FL",
    legalStatus: "MEDICAL",
    recLegal: false,
    medLegal: true,
    medPossessionLimit: "2.5 oz smokable every 35 days (physician may authorize more)",
    medQualifyingConditions: "Cancer, epilepsy, glaucoma, HIV/AIDS, PTSD, ALS, Crohn's, Parkinson's, MS, chronic pain, and others",
    medHowToApply: "Get recommendation from qualified physician, register with Florida Department of Health",
    officialResourceUrl: "https://knowthefactsmmj.com/",
    summaryText: "Florida has one of the largest medical cannabis programs. 2024 recreational ballot measure failed (needed 60%, got 56%).",
    penaltiesOverview: "Under 20g: Misdemeanor up to 1 year. Over 20g: Felony up to 5 years",
  },
  {
    name: "Hawaii",
    slug: "hawaii",
    abbreviation: "HI",
    legalStatus: "MEDICAL",
    recLegal: false,
    medLegal: true,
    medPossessionLimit: "4 oz",
    medHomeCultivation: "10 plants per patient (7 immature, 3 mature)",
    medQualifyingConditions: "Cancer, glaucoma, HIV/AIDS, PTSD, epilepsy, MS, Crohn's, rheumatoid arthritis, chronic pain, and others",
    medHowToApply: "Get certification from licensed physician, register with Hawaii Department of Health",
    officialResourceUrl: "https://health.hawaii.gov/medicalcannabis/",
    summaryText: "Hawaii has had medical cannabis since 2000. Patients can possess 4 oz and grow 10 plants.",
    penaltiesOverview: "Under 3g decriminalized ($130 fine). Over 3g: Criminal penalties",
  },
  {
    name: "Louisiana",
    slug: "louisiana",
    abbreviation: "LA",
    legalStatus: "MEDICAL",
    recLegal: false,
    medLegal: true,
    medPossessionLimit: "2.5 oz raw cannabis per 14 days",
    medHomeCultivation: "Not permitted",
    medQualifyingConditions: "Cancer, HIV/AIDS, cachexia, seizures, epilepsy, spasticity, Crohn's, MS, muscular dystrophy, PTSD, chronic pain, autism, and others",
    medHowToApply: "Get recommendation from licensed Louisiana physician, register with state pharmacy board",
    officialResourceUrl: "https://ldh.la.gov/page/MedMarijuana",
    summaryText: "Louisiana expanded medical cannabis to include smokable flower in 2022. Patients can possess 2.5 oz per 14 days.",
    penaltiesOverview: "First offense: Up to 15 days, $300 fine. Subsequent: Increased penalties",
  },
  {
    name: "New Hampshire",
    slug: "new-hampshire",
    abbreviation: "NH",
    legalStatus: "MEDICAL",
    recLegal: false,
    medLegal: true,
    medPossessionLimit: "2 oz",
    medHomeCultivation: "Not permitted",
    medQualifyingConditions: "Cancer, glaucoma, HIV/AIDS, hepatitis C, ALS, MS, Crohn's, PTSD, chronic pain, severe vomiting, and others",
    medHowToApply: "Get certification from provider, apply with Department of Health and Human Services",
    officialResourceUrl: "https://www.dhhs.nh.gov/programs-services/medicinal-and-therapeutic/therapeutic-cannabis-program",
    summaryText: "New Hampshire decriminalized recreational possession in 2017 but full legalization bills have repeatedly stalled.",
    penaltiesOverview: "Under 3/4 oz: $100 fine (decriminalized). Over 3/4 oz: Criminal penalties",
  },
  {
    name: "North Dakota",
    slug: "north-dakota",
    abbreviation: "ND",
    legalStatus: "MEDICAL",
    recLegal: false,
    medLegal: true,
    medPossessionLimit: "3 oz per 30 days",
    medHomeCultivation: "Not permitted",
    medQualifyingConditions: "Cancer, HIV/AIDS, hepatitis C, ALS, PTSD, Crohn's, fibromyalgia, epilepsy, terminal illness, chronic pain, and others",
    medHowToApply: "Get certification from healthcare provider, register with North Dakota Medical Marijuana Division",
    officialResourceUrl: "https://www.health.nd.gov/mm",
    summaryText: "North Dakota voters approved medical cannabis in 2016. 2024 recreational ballot measure failed.",
    penaltiesOverview: "Under 1/2 oz: Infraction, $1,000 fine. Over 1/2 oz: Misdemeanor or felony",
  },
  {
    name: "Oklahoma",
    slug: "oklahoma",
    abbreviation: "OK",
    legalStatus: "MEDICAL",
    recLegal: false,
    medLegal: true,
    medPossessionLimit: "3 oz on person, 8 oz at residence",
    medHomeCultivation: "6 mature, 6 seedlings per patient",
    medQualifyingConditions: "Any condition recommended by licensed physician (no specific list)",
    medHowToApply: "Get recommendation from licensed physician, apply with Oklahoma Medical Marijuana Authority",
    officialResourceUrl: "https://oklahoma.gov/omma.html",
    summaryText: "Oklahoma has one of the most accessible medical programs - no specific qualifying conditions required, just physician recommendation.",
    penaltiesOverview: "First offense possession: Misdemeanor, up to 1 year",
  },
  {
    name: "Pennsylvania",
    slug: "pennsylvania",
    abbreviation: "PA",
    legalStatus: "MEDICAL",
    recLegal: false,
    medLegal: true,
    medPossessionLimit: "30-day supply (determined by physician)",
    medHomeCultivation: "Not permitted",
    medQualifyingConditions: "Cancer, HIV/AIDS, ALS, epilepsy, glaucoma, IBD, MS, Parkinson's, PTSD, anxiety disorders, chronic pain, opioid use disorder, and others",
    medHowToApply: "Get certification from approved practitioner, register with PA Department of Health",
    officialResourceUrl: "https://www.pa.gov/agencies/health/patient-resources/medical-marijuana.html",
    summaryText: "Pennsylvania has medical cannabis but legalization bills continue to advance in the legislature.",
    penaltiesOverview: "Under 30g: Misdemeanor, up to 30 days. Over 30g: Misdemeanor up to 1 year",
  },
  {
    name: "Utah",
    slug: "utah",
    abbreviation: "UT",
    legalStatus: "MEDICAL",
    recLegal: false,
    medLegal: true,
    medPossessionLimit: "113g unprocessed cannabis (about 4 oz)",
    medHomeCultivation: "6 plants (only if 100+ miles from dispensary)",
    medQualifyingConditions: "Cancer, HIV/AIDS, MS, epilepsy, Crohn's, PTSD, ALS, autism, terminal illness, chronic pain, and others",
    medHowToApply: "Get recommendation from QMP, register with Utah Department of Health",
    officialResourceUrl: "https://medicalcannabis.utah.gov/",
    summaryText: "Utah voters approved medical cannabis in 2018. Home growing only allowed if living 100+ miles from dispensary.",
    penaltiesOverview: "Under 1 oz: Class B misdemeanor. Over 1 oz: Class A misdemeanor or felony",
  },
  {
    name: "West Virginia",
    slug: "west-virginia",
    abbreviation: "WV",
    legalStatus: "MEDICAL",
    recLegal: false,
    medLegal: true,
    medPossessionLimit: "30-day supply",
    medHomeCultivation: "Not permitted",
    medQualifyingConditions: "Cancer, HIV/AIDS, ALS, Parkinson's, MS, Crohn's, Huntington's, epilepsy, PTSD, chronic pain, and others",
    medHowToApply: "Get certification from registered physician, register with Office of Medical Cannabis",
    officialResourceUrl: "https://dhhr.wv.gov/bph/hsc/ommc/Pages/default.aspx",
    summaryText: "West Virginia legalized medical cannabis in 2017. Smoking flower is not permitted - only pills, oils, liquids, dermal patches, or vaporization.",
    penaltiesOverview: "Under 15g: Misdemeanor, up to 90 days. Over 15g: Felony",
  },

  // ============================================
  // CBD/LOW-THC ONLY STATES
  // ============================================
  {
    name: "Georgia",
    slug: "georgia",
    abbreviation: "GA",
    legalStatus: "CBD_ONLY",
    recLegal: false,
    medLegal: false,
    cbdOnlyProgram: true,
    cbdDetails: "Low-THC oil (up to 5% THC) for registered patients with qualifying conditions",
    medQualifyingConditions: "Cancer, ALS, seizure disorders, MS, Crohn's, Parkinson's, mitochondrial disease, and others",
    officialResourceUrl: "https://gmcc.georgia.gov/",
    summaryText: "Georgia allows low-THC oil (up to 5% THC) for registered patients. No dispensaries - must obtain elsewhere or grow (illegal).",
    penaltiesOverview: "Under 1 oz: Misdemeanor, up to 1 year. Over 1 oz: Felony, 1-10 years",
  },
  {
    name: "Indiana",
    slug: "indiana",
    abbreviation: "IN",
    legalStatus: "CBD_ONLY",
    recLegal: false,
    medLegal: false,
    cbdOnlyProgram: true,
    cbdDetails: "CBD products with 0.3% THC or less are legal",
    officialResourceUrl: "https://www.in.gov/",
    summaryText: "Indiana only allows CBD with 0.3% THC or less. All other cannabis remains illegal.",
    penaltiesOverview: "Under 30g: Misdemeanor, up to 1 year. Over 30g: Felony",
  },
  {
    name: "Iowa",
    slug: "iowa",
    abbreviation: "IA",
    legalStatus: "CBD_ONLY",
    recLegal: false,
    medLegal: false,
    cbdOnlyProgram: true,
    cbdDetails: "Medical CBD program with 4.5g THC per 90 days for registered patients",
    medQualifyingConditions: "Cancer, MS, seizures, AIDS/HIV, Crohn's, ALS, Parkinson's, terminal illness, chronic pain, PTSD, and others",
    officialResourceUrl: "https://idph.iowa.gov/omc",
    summaryText: "Iowa has a limited medical CBD program. THC-containing products capped at 4.5g per 90 days.",
    penaltiesOverview: "First offense: Serious misdemeanor, up to 6 months. Subsequent: Aggravated misdemeanor",
  },
  {
    name: "Kentucky",
    slug: "kentucky",
    abbreviation: "KY",
    legalStatus: "MEDICAL",
    recLegal: false,
    medLegal: true,
    medPossessionLimit: "To be determined - program launching January 2025",
    medQualifyingConditions: "Cancer, chronic pain, epilepsy, MS, chronic nausea, PTSD, and others",
    medHowToApply: "Program launching January 2025",
    officialResourceUrl: "https://kymedcan.ky.gov/",
    summaryText: "Kentucky legalized medical cannabis in 2023. Sales begin January 2025.",
    penaltiesOverview: "Under 8 oz: Class B misdemeanor. Over 8 oz: Felony",
  },
  {
    name: "Mississippi",
    slug: "mississippi",
    abbreviation: "MS",
    legalStatus: "MEDICAL",
    recLegal: false,
    medLegal: true,
    medPossessionLimit: "3 oz per month",
    medHomeCultivation: "Not permitted",
    medQualifyingConditions: "Cancer, epilepsy, PTSD, chronic pain, HIV/AIDS, ALS, MS, Parkinson's, sickle cell, and others",
    medHowToApply: "Get certification from licensed physician, register with Mississippi State Department of Health",
    officialResourceUrl: "https://msdh.ms.gov/page/30,0,420.html",
    summaryText: "Mississippi launched its medical cannabis program in 2022. Patients can possess up to 3 oz per month.",
    penaltiesOverview: "Under 30g: Misdemeanor, up to $250 fine. Over 30g: Felony",
  },
  {
    name: "South Dakota",
    slug: "south-dakota",
    abbreviation: "SD",
    legalStatus: "MEDICAL",
    recLegal: false,
    medLegal: true,
    medPossessionLimit: "3 oz",
    medHomeCultivation: "3 plants (only if 50+ miles from dispensary)",
    medQualifyingConditions: "Cancer, HIV/AIDS, hepatitis C, ALS, Crohn's, PTSD, cachexia, severe chronic pain, seizures, and others",
    medHowToApply: "Get certification from licensed physician, register with Department of Health",
    officialResourceUrl: "https://medcannabis.sd.gov/",
    summaryText: "South Dakota has medical cannabis. 2024 recreational ballot measure failed.",
    penaltiesOverview: "Under 2 oz: Misdemeanor, up to 1 year. Over 2 oz: Felony",
  },
  {
    name: "Texas",
    slug: "texas",
    abbreviation: "TX",
    legalStatus: "CBD_ONLY",
    recLegal: false,
    medLegal: false,
    cbdOnlyProgram: true,
    cbdDetails: "Compassionate Use Program: Low-THC cannabis (up to 1% THC) for registered patients",
    medQualifyingConditions: "Epilepsy, seizure disorders, MS, ALS, autism, terminal cancer, incurable neurodegenerative disease, PTSD",
    medHowToApply: "Get prescription from registered physician, purchase from licensed dispensary",
    officialResourceUrl: "https://www.texas.gov/health-services/compassionate-use-program/",
    summaryText: "Texas has a very limited low-THC program (up to 1% THC). Broader medical or recreational cannabis remains illegal.",
    penaltiesOverview: "Under 2 oz: Class B misdemeanor, up to 180 days. Over 2 oz: Increasingly severe felony charges",
  },
  {
    name: "Wisconsin",
    slug: "wisconsin",
    abbreviation: "WI",
    legalStatus: "CBD_ONLY",
    recLegal: false,
    medLegal: false,
    cbdOnlyProgram: true,
    cbdDetails: "CBD with no more than 0.3% THC is legal. No medical marijuana program.",
    officialResourceUrl: "https://www.dhs.wisconsin.gov/",
    summaryText: "Wisconsin only allows CBD with 0.3% THC or less. Medical and recreational cannabis remain illegal.",
    penaltiesOverview: "First offense: Misdemeanor, up to 6 months. Subsequent: Felony, up to 3.5 years",
  },
  {
    name: "Wyoming",
    slug: "wyoming",
    abbreviation: "WY",
    legalStatus: "CBD_ONLY",
    recLegal: false,
    medLegal: false,
    cbdOnlyProgram: true,
    cbdDetails: "CBD from hemp with 0.3% THC or less is legal. No medical program.",
    officialResourceUrl: "https://health.wyo.gov/",
    summaryText: "Wyoming allows hemp-derived CBD with 0.3% THC or less. All other cannabis is illegal.",
    penaltiesOverview: "Under 3 oz: Misdemeanor, up to 1 year. Over 3 oz: Felony",
  },

  // ============================================
  // FULLY ILLEGAL STATES
  // ============================================
  {
    name: "Idaho",
    slug: "idaho",
    abbreviation: "ID",
    legalStatus: "ILLEGAL",
    recLegal: false,
    medLegal: false,
    cbdOnlyProgram: false,
    officialResourceUrl: "https://isp.idaho.gov/",
    summaryText: "Idaho has some of the strictest cannabis laws in the nation. All cannabis including CBD with any THC is illegal.",
    penaltiesOverview: "Under 3 oz: Misdemeanor, up to 1 year. Over 3 oz: Felony, up to 5 years. Any amount of concentrate: Felony",
  },
  {
    name: "Kansas",
    slug: "kansas",
    abbreviation: "KS",
    legalStatus: "ILLEGAL",
    recLegal: false,
    medLegal: false,
    cbdOnlyProgram: false,
    cbdDetails: "CBD from hemp with 0% THC may be legal",
    officialResourceUrl: "https://www.kansas.gov/",
    summaryText: "Kansas has no medical or recreational cannabis program. Legislation continues to be proposed but has not passed.",
    penaltiesOverview: "First offense: Class B misdemeanor, up to 6 months. Subsequent: Increasingly severe",
  },
  {
    name: "Nebraska",
    slug: "nebraska",
    abbreviation: "NE",
    legalStatus: "DECRIMINALIZED",
    recLegal: false,
    medLegal: false,
    cbdOnlyProgram: false,
    cbdDetails: "CBD from hemp with 0.3% THC or less is legal. 2024 medical cannabis ballot measures approved but facing legal challenges.",
    officialResourceUrl: "https://dhhs.ne.gov/",
    summaryText: "Nebraska has decriminalized small amounts but has no legal cannabis program. 2024 medical ballot measures are being challenged in court.",
    penaltiesOverview: "First offense under 1 oz: Infraction, $300 fine. Subsequent: Misdemeanor",
  },
  {
    name: "North Carolina",
    slug: "north-carolina",
    abbreviation: "NC",
    legalStatus: "DECRIMINALIZED",
    recLegal: false,
    medLegal: false,
    cbdOnlyProgram: true,
    cbdDetails: "CBD from hemp with less than 0.3% THC is legal. Limited epilepsy CBD program exists.",
    officialResourceUrl: "https://www.ncdhhs.gov/",
    summaryText: "North Carolina has decriminalized small amounts. A limited CBD program exists for epilepsy. Medical cannabis legislation pending.",
    penaltiesOverview: "Under 0.5 oz: Class 3 misdemeanor (decriminalized). Over 0.5 oz: Class 1 misdemeanor",
  },
  {
    name: "South Carolina",
    slug: "south-carolina",
    abbreviation: "SC",
    legalStatus: "ILLEGAL",
    recLegal: false,
    medLegal: false,
    cbdOnlyProgram: false,
    cbdDetails: "CBD from hemp with 0.3% THC or less is technically legal under federal farm bill",
    officialResourceUrl: "https://scdhec.gov/",
    summaryText: "South Carolina has no medical or recreational cannabis program. Limited medical legislation has been proposed but not passed.",
    penaltiesOverview: "First offense (up to 1 oz): Misdemeanor, up to 30 days. Subsequent: Up to 1 year",
  },
  {
    name: "Tennessee",
    slug: "tennessee",
    abbreviation: "TN",
    legalStatus: "ILLEGAL",
    recLegal: false,
    medLegal: false,
    cbdOnlyProgram: true,
    cbdDetails: "CBD from hemp with 0.3% THC or less is legal. Very limited medical program for epilepsy (CBD oil only).",
    officialResourceUrl: "https://www.tn.gov/health.html",
    summaryText: "Tennessee allows hemp CBD and has a very limited CBD-only program for epilepsy. No broader medical or recreational program.",
    penaltiesOverview: "Under 0.5 oz: Class A misdemeanor, up to 1 year. Over 0.5 oz: Felony",
  },

  // Additional Medical States
  {
    name: "Arizona (Neighboring)",
    slug: "Arizona",
    abbreviation: "AZ",
    // Already included above
  },
];

// Export for seed script
export default stateData;
